### ISSUE TITLE
Decrease header file size even more!

### ISSUE THREAD

**Issue by GuntisTreulands** [ricardo-rendoncepeda/mtl2opengl#1]
This is not really an issue (and can be closed at once) - but a simple suggestion - when generating header file arrays, remove unnecessary spaces between floats in arrays:

  0.123, -0.134, 0.339,      =>
0.123,-0.134,0.339,

This reduced header file I generated - from 49mb to 41 mb.

**Comment by GuntisTreulands** [comment]
As it is not really a bug, but only a suggestion, I will close it.

**Comment by ricardo-rendoncepeda** [comment]
The repository has been extensively updated and your suggestion made it into Version 1.3 :)
Thanks for using mtl2opengl - I hope it's been useful!
