### ISSUE TITLE
Depth of field seems wrong...

### ISSUE THREAD

**Issue by equinox2k** [ricardo-rendoncepeda/mtl2opengl#3]
It appears that objects get bigger in the distance rather than the conventional smaller so things can look a bit confusing.

**Comment by equinox2k** [comment]
Ok found a solution, i did not understand at first what orthog was

changed...

_projectionMatrix = GLKMatrix4MakeOrtho(-1.0, 1.0, -1.0/aspectRatio, 1.0/aspectRatio, 0.1, 10.1);

to...

 _projectionMatrix = GLKMatrix4MakePerspective(DEG2RAD(45), aspectRatio, .01, 1000);

using the following define...

#define DEG2RAD(angle) ((angle) / 180.0f \* (float)M_PI)

**Comment by ricardo-rendoncepeda** [comment]
Ah yes, good spot!
I was messing around with the projection matrix and forgot to change the Orthographic implementation back to Perspective.

Changed...

```
_projectionMatrix = GLKMatrix4MakeOrtho(-1.0, 1.0, -1.0/aspectRatio, 1.0/aspectRatio, 0.1, 10.1);
```

To...

```
_projectionMatrix = GLKMatrix4MakePerspective(GLKMathDegreesToRadians(45.0), aspectRatio, 0.1, 10.1);
```

**Comment by equinox2k** [comment]
Glad I could help :). Thanks for providing such a great project, has really helped me get into OpenGL where I have struggled before. So far I've managed to add bump mapping to object now trying to work out how to add a shadow.

**Comment by ricardo-rendoncepeda** [comment]
Thanks for the kind comments! Bump mapping is a pretty powerful and useful technique - you should try implementing "displacement mapping" too. I don't have anything on shadows at the moment, but I'd love to see your results in the future :)
