### ISSUE TITLE
How to load multiple Texture in the code

### ISSUE THREAD

**Issue by mihirpmehta** [ricardo-rendoncepeda/mtl2opengl#4]
Hi ,

 I have around 24 images and all are separate one. I have MTL file for the same. I have generated .h for obj and mtl now i don't know hoe to load textures from your sample code. 

In the sample code textures was loaded like 
[self loadTexture:@"cube.png"];

But i have separate 24 images . I don't know hot to load each of them. 
#2

Do i need to alter .vsh and .fsh files for this ?

**Comment by ricardo-rendoncepeda** [comment]
Hi @mihirpmehta 

24 textures are far too many  for a single vertex/fragment shader pair. The most I've seen is maybe 3 (diffuse map, specular map, bump map) and never exceeding 8.

Do you have 24 textures for one single model? If so, I recommend packing all the textures into a single texture atlas (http://en.wikipedia.org/wiki/Texture_atlas) and retexturing your model to fit on a single texture grid.

If you have 24 models, each with one texture, then you would just need to render the 24 models individually.

**Comment by ricardo-rendoncepeda** [comment]
As I mentioned in issue #2 ...

"The script wasn't designed with multiple textures in mind..."

I'm happy to offer advice for multitexturing, but this really exceeds the scope of `mtl2opengl`.

**Comment by mihirpmehta** [comment]
Hi , 

Thanks Ricardo .. even though i am developing in Objective C/C++ since last 5 years, I am completely new to OPEN GL ES. and developing in OPEN GL ES is hard compare to plain objective C or C++. 

I will work on your suggestion. Still to be clear in plain language I  want to load 24 different images on one 3d Object.Just to be confirm that we are on same page.

**Comment by ricardo-rendoncepeda** [comment]
OpenGL ES indeed has a very steep learning curve, but you can solve your problem without it. Taking the cube example, you can think of each color as one different image (6 total) mapped onto a particular face (also 6 total). So, with some clever texture mapping in your 3D modeling software of choice, you can fit all 24 images into 1 big image.

Overall, I would say this is more of an artistic problem than a technical one. So more 3D modeling, less 3D coding :)

**Comment by mihirpmehta** [comment]
Thanks I will try that ... :)
